name: "Audit CI"

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
      - 'feat/**'

permissions:
  contents: read

jobs:
  build:
    name: 'Audit CI'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: JohnnyMorganz/stylua-action@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          version: latest
          args: false
      - run: |
          stylua --version
